#!/usr/bin/ruby

# This is the most basic example of usage shown in upstream's README file.

require 'ffi'

module MyLib
  extend FFI::Library
  ffi_lib 'c'
  attach_function :puts, [ :string ], :int
end

MyLib.puts 'Hello, World using libc!'
